[package]
name = "ssllib-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1obj = { path = "../asn1obj/asn1obj"}
asn1obj_codegen = { path = "../asn1obj/asn1obj_codegen"}
