#! /bin/bash

scriptfile=`readlink -f $0`
scriptdir=`dirname $scriptfile`
cadir=$scriptdir/ca


if [ ! -d $cadir ]
then
	mkdir -p $cadir
fi

openssl genrsa -out $cadir/root.key 4096

cat  > $cadir/root_req.config <<EOF
[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
countryName = US
commonName  = Test Root CA
EOF

openssl req -new -key $cadir/root.key -out $cadir/root.csr -config $cadir/root_req.config

cat > $cadir/ca.ext <<EOF
[ default ]
basicConstraints = critical,CA:true     # recommended to be marked critical. required for a ca
keyUsage         = critical,keyCertSign # required to be marked critical. required for signing certs
EOF

cat > $cadir/root.config <<EOF
[ ca ]
default_ca      = CA_default

[ CA_default]
dir             = $cadir/root_ca      # helper variable pointing to ca specific files
database        = \$dir/index     # database of certs generated by the ca
new_certs_dir   = $cadir/             # one dir up to make the demo easier
certificate     = $cadir/root.pem     # one dir up to make the demo easier
serial          = \$dir/serial    # file with incrementing hex serial number for certs
private_key     = $cadir/root.key

policy          = policy_any
email_in_dn     = no             # recommended
unique_subject  = no             # recommended for easier certificate rollover
copy_extensions = none           # don't honor the extensions in the csr
default_md      = sha256

[ policy_any ]
countryName            = optional
stateOrProvinceName    = optional
organizationName       = optional
organizationalUnitName = optional
commonName             = supplied

EOF

if [ ! -d $cadir/root_ca ]
then
	mkdir -p $cadir/root_ca
fi

touch $cadir/root_ca/index

echo "00" > $cadir/root_ca/serial

openssl ca -batch -in $cadir/root.csr -out $cadir/root.pem -config $cadir/root.config -selfsign -extfile $cadir/ca.ext -days 1095


openssl genrsa -out $cadir/intermediate.key 4096

cat >$cadir/intermediate_req.config <<EOF
[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
countryName = US
commonName  = Test Intermediate CA
EOF

openssl req -new -key $cadir/intermediate.key -out $cadir/intermediate.csr -config $cadir/intermediate_req.config


openssl ca -batch -in $cadir/intermediate.csr -out $cadir/intermediate.pem -config $cadir/root.config -extfile $cadir/ca.ext -days 730


openssl genrsa -out $cadir/leaf.key 4096


cat > $cadir/leaf_req.config <<EOF
[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
countryName = US
commonName  = Test Leaf
EOF

openssl req -new -key $cadir/leaf.key -out $cadir/leaf.csr -config $cadir/leaf_req.config

cat > $cadir/intermediate.config <<EOF
[ ca ]
default_ca      = CA_default

[ CA_default]
dir             = $cadir/intermediate_ca   # helper variable pointing to ca specific files
database        = \$dir/index          # database of certs generated by the ca
new_certs_dir   = $cadir/                  # one dir up to make the demo easier
certificate     = $cadir/intermediate.pem  # one dir up to make the demo easier
serial          = \$dir/serial         # file with incrementing hex serial number for certs
private_key     = $cadir/intermediate.key

policy          = policy_any
email_in_dn     = no                  # recommended
unique_subject  = no                  # recommended for easier certificate rollover
copy_extensions = none                # don't honor the extensions in the csr
default_md      = sha256

[ policy_any ]
countryName            = optional
stateOrProvinceName    = optional
organizationName       = optional
organizationalUnitName = optional
commonName             = supplied
EOF

if [ ! -d $cadir/intermediate_ca ]
then
	mkdir -p $cadir/intermediate_ca
fi

touch $cadir/intermediate_ca/index

echo "00" > $cadir/intermediate_ca/serial

openssl ca -batch -in $cadir/leaf.csr -out $cadir/leaf.pem -config $cadir/intermediate.config -days 365

openssl verify -x509_strict -CAfile $cadir/root.pem -untrusted $cadir/intermediate.pem $cadir/leaf.pem